<?php

namespace Database\Seeders;

use App\Models\Notification;
use Illuminate\Database\Seeder;

class NotificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $notifications = [
            [
                'identifier' => 'notif-hadits-kategori-filter',
                'title' => 'Fitur Baru: Filter Kategori & Bab Hadits',
                'message' => 'Pilih dan telusuri hadits berdasarkan tema/bab (Iman, Shalat, Zakat, Puasa, Nikah, dll.) dengan katalog topik cepat di Hadits Reader & Hadits Hub.',
                'link' => '/hadits',
                'category' => 'Fitur Baru',
                'type' => 'feature',
                'badge_icon' => 'book',
                'badge_color' => 'bg-emerald-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'new',
                'time_ago' => 'Baru saja',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'published_at' => '2026-10-05 09:30:00',
            ],
            [
                'identifier' => 'notif-seo-rich-snippets',
                'title' => 'Optimasi SEO & Google Rich Snippets',
                'message' => 'Pencarian ayat & juz makin mudah di Google dengan skema FAQPage tanya-jawab, breadcrumb terstruktur, dan navigasi langsung per nomor ayat.',
                'link' => '/surah',
                'category' => 'SEO & Schema',
                'type' => 'feature',
                'badge_icon' => 'sparkles',
                'badge_color' => 'bg-blue-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'new',
                'time_ago' => '30 menit lalu',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'published_at' => '2026-10-05 09:00:00',
            ],
            [
                'identifier' => 'notif-penanda-hadits-baru',
                'title' => 'Penanda Hadits Nabawi Kini Tersedia',
                'message' => 'Kini Anda dapat menandai hadits pilihan, menyimpan hadits favorit, dan menuliskan catatan tadabbur & faidah hadits di halaman Penanda.',
                'link' => '/penanda?type=hadits',
                'category' => 'Fitur Baru',
                'type' => 'bookmark',
                'badge_icon' => 'bookmark',
                'badge_color' => 'bg-amber-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'new',
                'time_ago' => '1 jam lalu',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 3,
                'published_at' => '2026-10-05 08:00:00',
            ],
            [
                'identifier' => 'notif-hadits-7-kitab',
                'title' => 'Koleksi 7 Kitab Hadits Mu\'tamad & Syarah',
                'message' => 'Telah hadir 33.137 hadits dari 7 kitab mu\'tamad (Shahih Bukhari, Muslim, Abu Daud, Tirmidzi, An-Nasa\'i, Ibnu Majah, Musnad Ahmad) dengan teks Arab terstandarisasi & penjelasan syarah.',
                'link' => '/hadits',
                'category' => 'Hadits Nabawi',
                'type' => 'feature',
                'badge_icon' => 'book',
                'badge_color' => 'bg-teal-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'new',
                'time_ago' => '2 jam lalu',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
                'published_at' => '2026-10-05 07:00:00',
            ],
            [
                'identifier' => 'notif-version-2-32-0',
                'title' => 'Pembaruan IndoQuran Versi 2.32.0',
                'message' => 'Filter kategori hadits, Google Rich Snippets komprehensif, navigasi kanonikal per nomor ayat, dedicated sitemap topik hadits, dan ketahanan cache Redis.',
                'link' => '/riwayat-versi',
                'category' => 'Riwayat Versi',
                'type' => 'version',
                'badge_icon' => 'check',
                'badge_color' => 'bg-indigo-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'new',
                'time_ago' => 'Hari ini',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 5,
                'published_at' => '2026-10-05 06:00:00',
            ],
            [
                'identifier' => 'notif-audio-arabic-speech',
                'title' => 'Audio Pelafalan Arab di Browser',
                'message' => 'Dengarkan suara pelafalan teks Arab seketika pada Hadits & Doa Bersama langsung di browser Anda menggunakan Web Speech API tanpa konsumsi kuota server.',
                'link' => '/hadits',
                'category' => 'Audio Player',
                'type' => 'audio',
                'badge_icon' => 'speaker',
                'badge_color' => 'bg-blue-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'earlier',
                'time_ago' => 'Kemarin',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 6,
                'published_at' => '2026-10-04 14:00:00',
            ],
            [
                'identifier' => 'notif-doa-bersama-audio',
                'title' => 'Doa Bersama Dilengkapi Tombol Audio',
                'message' => 'Setiap doa harian dan dzikir kini dapat diputar audio pelafalannya dengan tombol play instan untuk mempermudah menghafal dan bertilawah.',
                'link' => '/doa-bersama',
                'category' => 'Doa & Dzikir',
                'type' => 'prayer',
                'badge_icon' => 'prayer',
                'badge_color' => 'bg-rose-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'earlier',
                'time_ago' => '2 hari lalu',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 7,
                'published_at' => '2026-10-03 12:00:00',
            ],
            [
                'identifier' => 'notif-khatam-tracker-30juz',
                'title' => 'Rencanakan Target Khatam 30 Juz',
                'message' => 'Gunakan fitur Khatam Tracker di halaman Penanda untuk mencatat progres membaca harian Anda menuju khatam Al-Quran.',
                'link' => '/penanda',
                'category' => 'Tilawah',
                'type' => 'tracker',
                'badge_icon' => 'target',
                'badge_color' => 'bg-purple-600',
                'image' => '/images/logo-icon.webp',
                'section' => 'earlier',
                'time_ago' => '3 hari lalu',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 8,
                'published_at' => '2026-10-02 09:00:00',
            ],
            [
                'identifier' => 'notif-tafsir-maudhui-update',
                'title' => 'Kajian Tematik Tafsir Maudhu\'i',
                'message' => 'Temukan himpunan ayat per topik kehidupan (Ketenangan Hati, Rezeki, Keluarga Sakinah, Birrul Walidain) dengan mudah.',
                'link' => '/tafsir-maudhui',
                'category' => 'Tafsir Al-Quran',
                'type' => 'tafsir',
                'badge_icon' => 'sparkles',
                'badge_color' => 'bg-amber-500',
                'image' => '/images/logo-icon.webp',
                'section' => 'earlier',
                'time_ago' => '4 hari lalu',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 9,
                'published_at' => '2026-10-01 10:00:00',
            ],
            [
                'identifier' => 'notif-pwa-mobile-install',
                'title' => 'Install IndoQuran di Layar HP',
                'message' => 'Aplikasi IndoQuran mendukung Progressive Web App (PWA). Tambahkan ke layar utama smartphone untuk akses cepat dan bacaan offline.',
                'link' => '/riwayat-versi',
                'category' => 'Aplikasi Web',
                'type' => 'system',
                'badge_icon' => 'mobile',
                'badge_color' => 'bg-emerald-500',
                'image' => '/images/logo-icon.webp',
                'section' => 'earlier',
                'time_ago' => '5 hari lalu',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 10,
                'published_at' => '2026-09-30 11:00:00',
            ],
        ];

        foreach ($notifications as $data) {
            Notification::updateOrCreate(
                ['identifier' => $data['identifier']],
                $data
            );
        }
    }
}
